
cosmos: 
  container: rating_caching
  database: TSS_CosmosDB
  queryMetricsEnabled: true
  uri: "https://eastus2-fxs-victor-np-cosmosdb-cdba.documents.azure.com:443/"
emporio-transport.rating.crsv: 
  cache: false
  staticaccount: false
  urls: "http://localhost:3001"
feign: 
  hystrix: 
    enabled: true
  url: "http://localhost:3001"

hystrix: 
  command: 
    circuitBreaker: 
      errorThresholdPercentage: 100
      requestVolumeThreshold: 1
      sleepWindowInMilliseconds: 10000
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 10000
            
management.endpoints.web.exposure.include: "health,info,metrics,refresh"

spring.security.oauth2.resourceserver.jwt: 
  issuer-uri: "https://sts.windows.net/ef29fa23-67e1-4363-8f49-6c521029bd71/"

message: dev
