management.endpoints.web.exposure.include: health,info,metrics
spring.security.oauth2.resourceserver.jwt:
    issuer-uri: https://sts.windows.net/ef29fa23-67e1-4363-8f49-6c521029bd71/
    
emporio-transport.rating.crsv.urls: http://127.0.0.1:3001
message: 'hello to Dev profile'